services:
    yogabi:
        build: ./
        volumes:
            - .:/react-app
            - ~/.aws:/home/node/.aws
        ports:
            - "3000:3000"
        command:
            - /bin/sh
            - -c
            - |
                npm install
                npm run dev