service: yogabi-react

provider:
    name: aws
    runtime: nodejs20.x
    region: eu-central-1

plugins:
    - serverless-s3-sync

custom:
    bucketName: serverless-yogabi-react
    s3Sync:
        - bucketName: ${self:custom.bucketName}
          localDir: out/

resources:
    Resources:
        ReactAppBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.bucketName}
                PublicAccessBlockConfiguration:
                    BlockPublicAcls: false
                OwnershipControls:
                    Rules:
                        -   ObjectOwnership: ObjectWriter
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html
        S3AccessPolicy:
            Type: AWS::S3::BucketPolicy
            Properties:
                Bucket:
                    Ref: ReactAppBucket
                PolicyDocument:
                    Statement:
                        - Sid: PublicReadGetObject
                          Effect: Allow
                          Principal: "*"
                          Action:
                              - s3:GetObject
                          Resource: arn:aws:s3:::${self:custom.bucketName}/*
        CloudFrontDistribution:
            Type: AWS::CloudFront::Distribution
            Properties:
                DistributionConfig:
                    Origins:
                        - DomainName: ${self:custom.bucketName}.s3.${self:provider.region}.amazonaws.com
                          Id: ReactApp
                          CustomOriginConfig:
                              HTTPPort: 80
                              HTTPSPort: 443
                              OriginProtocolPolicy: https-only
                    Enabled: "true"
                    DefaultRootObject: index.html
                    CustomErrorResponses:
                        - ErrorCode: 404
                          ResponseCode: 200
                          ResponsePagePath: /index.html
                        -   ErrorCode: 403
                            ResponseCode: 200
                            ResponsePagePath: /index.html
                    DefaultCacheBehavior:
                        AllowedMethods:
                            - DELETE
                            - GET
                            - HEAD
                            - OPTIONS
                            - PATCH
                            - POST
                            - PUT
                        TargetOriginId: ReactApp
                        ForwardedValues:
                            QueryString: "false"
                            Cookies:
                                Forward: none
                        ViewerProtocolPolicy: redirect-to-https
                    ViewerCertificate:
                        CloudFrontDefaultCertificate: true